In [1]:
import pandas as pd 
import numpy as np

In [2]:
#!pip install numpy

In [3]:
movies = pd.read_csv('dataset\movie.csv')
credits = pd.read_csv('dataset\credits.csv')

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:2: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:2: SyntaxWarning: invalid escape sequence '\c'
C:\Users\infor\AppData\Local\Temp\ipykernel_8028\1661109425.py:1: SyntaxWarning: invalid escape sequence '\m'
  movies = pd.read_csv('dataset\movie.csv')
C:\Users\infor\AppData\Local\Temp\ipykernel_8028\1661109425.py:2: SyntaxWarning: invalid escape sequence '\c'
  credits = pd.read_csv('dataset\credits.csv')

In [4]:
movies.head(2)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."

In [5]:
credits.head(2)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844

In [6]:
merged_df = pd.merge(movies, credits, on='id', how='inner')
merged_df.to_csv('merged_dataset.csv', index=False)
merged_df.head(2)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords,cast,crew
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...","[{'cast_id': 9, 'character': 'Joseph Cooper', ...","[{'credit_id': '54cba75b925141678e014d1a', 'de..."

In [7]:
df = pd.read_csv('merged_dataset.csv')

In [8]:
df.head(2)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords,cast,crew
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,...","[{'cast_id': 9, 'character': 'Joseph Cooper', ...","[{'credit_id': '54cba75b925141678e014d1a', 'de..."

In [9]:
df['cast'][0]

'[{\'cast_id\': 1, \'character\': \'Dom Cobb\', \'credit_id\': \'52fe4534c3a368484e04de03\', \'gender\': 2, \'id\': 6193, \'name\': \'Leonardo DiCaprio\', \'order\': 0, \'profile_path\': \'/jToSMocaCaS5YnuOJVqQ7S7pr4Q.jpg\'}, {\'cast_id\': 3, \'character\': \'Arthur\', \'credit_id\': \'52fe4534c3a368484e04de0b\', \'gender\': 2, \'id\': 24045, \'name\': \'Joseph Gordon-Levitt\', \'order\': 1, \'profile_path\': \'/zSuXCR6xCKIgo0gWLdp8moMlH3I.jpg\'}, {\'cast_id\': 5, \'character\': \'Ariadne\', \'credit_id\': \'52fe4534c3a368484e04de13\', \'gender\': 1, \'id\': 27578, \'name\': \'Ellen Page\', \'order\': 2, \'profile_path\': \'/paexwBfmlVyzva7q4XgcBdqowmL.jpg\'}, {\'cast_id\': 7, \'character\': \'Eames\', \'credit_id\': \'52fe4534c3a368484e04de1b\', \'gender\': 2, \'id\': 2524, \'name\': \'Tom Hardy\', \'order\': 3, \'profile_path\': \'/4CR1D9VLWZcmGgh4b6kKuY2NOel.jpg\'}, {\'cast_id\': 2, \'character\': \'Saito\', \'credit_id\': \'52fe4534c3a368484e04de07\', \'gender\': 2, \'id\': 3899, \'name\': \'Ken Watanabe\', \'order\': 4, \'profile_path\': \'/v8WQ5wCIZsnqVZn7jQveaDqurox.jpg\'}, {\'cast_id\': 8, \'character\': \'Robert Fischer\', \'credit_id\': \'52fe4534c3a368484e04de1f\', \'gender\': 2, \'id\': 2037, \'name\': \'Cillian Murphy\', \'order\': 5, \'profile_path\': \'/gybXt7gjFCeV67l3jgJtp6Pxm77.jpg\'}, {\'cast_id\': 4, \'character\': \'Mal\', \'credit_id\': \'52fe4534c3a368484e04de0f\', \'gender\': 1, \'id\': 8293, \'name\': \'Marion Cotillard\', \'order\': 6, \'profile_path\': \'/wuEWDK1D2v26KRDIY7DTHBaSdwA.jpg\'}, {\'cast_id\': 6, \'character\': \'Miles\', \'credit_id\': \'52fe4534c3a368484e04de17\', \'gender\': 2, \'id\': 3895, \'name\': \'Michael Caine\', \'order\': 7, \'profile_path\': \'/vvj0JMSFpOajXCE46Hy4dyqSP2U.jpg\'}, {\'cast_id\': 19, \'character\': \'Yusuf\', \'credit_id\': \'52fe4534c3a368484e04de4f\', \'gender\': 2, \'id\': 95697, \'name\': \'Dileep Rao\', \'order\': 8, \'profile_path\': \'/lsnmeKueImKeToe4oNo4YWie4aM.jpg\'}, {\'cast_id\': 9, \'character\': \'Browning\', \'credit_id\': \'52fe4534c3a368484e04de23\', \'gender\': 2, \'id\': 13022, \'name\': \'Tom Berenger\', \'order\': 9, \'profile_path\': \'/gueEBgqv1sWFemMXyI4TJ2peuMA.jpg\'}, {\'cast_id\': 22, \'character\': \'Maurice Fischer\', \'credit_id\': \'52fe4534c3a368484e04de59\', \'gender\': 2, \'id\': 4935, \'name\': \'Pete Postlethwaite\', \'order\': 10, \'profile_path\': \'/5nbSzrwyDcLhC15buncGdrQqJ8e.jpg\'}, {\'cast_id\': 10, \'character\': \'Nash\', \'credit_id\': \'52fe4534c3a368484e04de27\', \'gender\': 2, \'id\': 526, \'name\': \'Lukas Haas\', \'order\': 11, \'profile_path\': \'/1n1CTF6fi52BF407iQU6aMMKWFU.jpg\'}, {\'cast_id\': 89, \'character\': \'Blonde\', \'credit_id\': \'52fe4534c3a368484e04de99\', \'gender\': 1, \'id\': 66441, \'name\': \'Talulah Riley\', \'order\': 12, \'profile_path\': \'/cmA8krd4hpPC9kWSF9wpSx6ffMt.jpg\'}, {\'cast_id\': 92, \'character\': \'Japanese Security Guard\', \'credit_id\': \'57d488dec3a3685568007ba1\', \'gender\': 0, \'id\': 173212, \'name\': \'Tohoru Masamune\', \'order\': 13, \'profile_path\': \'/hCevJsAh0RByhKzRZwrGXlW64Oo.jpg\'}, {\'cast_id\': 93, \'character\': \'Phillipa (5 years)\', \'credit_id\': \'57d488f8c3a368154b0011a1\', \'gender\': 1, \'id\': 967376, \'name\': \'Taylor Geare\', \'order\': 14, \'profile_path\': \'/2ITSJXHWdkAFWu1hqIfr53zib8J.jpg\'}, {\'cast_id\': 94, \'character\': \'Phillipa (3 years)\', \'credit_id\': \'57d48919925141382f0011ca\', \'gender\': 1, \'id\': 973135, \'name\': \'Claire Geare\', \'order\': 15, \'profile_path\': \'/gLU4bc2Cr7GgLeIaZJwihmDcJ64.jpg\'}, {\'cast_id\': 95, \'character\': \'James (3 years)\', \'credit_id\': \'57d48aca925141369d00113d\', \'gender\': 2, \'id\': 1677266, \'name\': \'Johnathan Geare\', \'order\': 16, \'profile_path\': \'/zorFsXj371juf6S9RuX2OxOWfaP.jpg\'}, {\'cast_id\': 96, \'character\': "Saito\'s Attendant", \'credit_id\': \'57d48b45c3a3680b9f00179e\', \'gender\': 2, \'id\': 56120, \'name\': \'Yuji Okumoto\', \'order\': 17, \'profile_path\': \'/eVq0Od53a8JdfYLGHxkBboOtsIe.jpg\'}, {\'cast_id\': 97, \'character\': \'Elderly Bald Man\', \'credit_id\': \'57d48b59c3a3685568007cd7\', \'gender\': 2, \'id\': 2246, \'name\': \'Earl Cameron\', \'order\': 18, \'profile_path\': \'/4bDKeRU96RxpJ2Uv8x2yrjCmGks.jpg\'}, {\'cast_id\': 98, \'character\': \'Lawyer\', \'credit_id\': \'57d48b6dc3a3680ccd001433\', \'gender\': 2, \'id\': 1677267, \'name\': \'Ryan Hayward\', \'order\': 19, \'profile_path\': \'/i43V4v95o2n60HSmcHuiYWbHAVT.jpg\'}, {\'cast_id\': 99, \'character\': \'Flight Attendant\', \'credit_id\': \'57d48b84925141382f0012af\', \'gender\': 1, \'id\': 1334309, \'name\': \'Miranda Nolan\', \'order\': 20, \'profile_path\': \'/lwIOE3hSz4M3l3dab0UrhoK2Xt6.jpg\'}, {\'cast_id\': 100, \'character\': \'Cab Driver\', \'credit_id\': \'57d53da09251415c1e000263\', \'gender\': 2, \'id\': 535, \'name\': \'Russ Fega\', \'order\': 21, \'profile_path\': \'/7JFQueMbXqGIz16wKBlok7WfNNz.jpg\'}, {\'cast_id\': 101, \'character\': \'Thin Man\', \'credit_id\': \'57d53db4c3a368556800ce41\', \'gender\': 2, \'id\': 72864, \'name\': \'Tim Kelleher\', \'order\': 22, \'profile_path\': \'/y1sYHWkXNeW09Iy2BUed4SveKl7.jpg\'}, {\'cast_id\': 102, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53e46c3a36812b2000308\', \'gender\': 1, \'id\': 1677498, \'name\': \'Coralie Dedykere\', \'order\': 23, \'profile_path\': \'/kv7RsuDTCYpPpIkadtx9sXkEENw.jpg\'}, {\'cast_id\': 103, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53ee6c3a3686e3c000cd9\', \'gender\': 0, \'id\': 13695, \'name\': \'Silvie Laguna\', \'order\': 24, \'profile_path\': \'/rbigEHdNk1DBAgj9ge7Q1CqhdFD.jpg\'}, {\'cast_id\': 104, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53efcc3a36813230002f5\', \'gender\': 2, \'id\': 133257, \'name\': \'Virgile Bramly\', \'order\': 25, \'profile_path\': \'/bHtRBA6UNeePq9LXk6vwzNNbIYs.jpg\'}, {\'cast_id\': 105, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53fde9251415c1e000324\', \'gender\': 2, \'id\': 1677507, \'name\': \'Nicolas Clerc\', \'order\': 26, \'profile_path\': \'/aYchs3lYO9RvhmClO1xLkocTFZq.jpg\'}, {\'cast_id\': 106, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d5405f9251415bb300037f\', \'gender\': 2, \'id\': 1536351, \'name\': \'Jean-Michel Dagory\', \'order\': 27, \'profile_path\': \'/wU0a4eyOlIinZVGnbIs98KRFo9D.jpg\'}, {\'cast_id\': 107, \'character\': \'Lobby Sub Con\', \'credit_id\': \'57d540c7c3a36813230003bc\', \'gender\': 2, \'id\': 203087, \'name\': \'Marc Raducci\', \'order\': 28, \'profile_path\': \'/amulXn9DCowb8OGZJMrcw34qSYZ.jpg\'}]'

In [10]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords', 'cast', 'crew'],
      dtype='object')

In [11]:
credits.head(1)['crew'].values

array(['[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': 

In [12]:
#removing these columns
# budget,homepage, runtime, backdrop_path, poster_path, original_language ("lookin at this column we find that its imbalanced with english is more than 60% of data points")
# original_title, popularity, production_companies, production_countries, release_date, revenue, spoken_lang, status, tagline, vote 
df['original_language'].value_counts()

original_language
en    29902
fr     2661
it     1755
ja     1452
es     1157
      ...
si        1
qu        1
sm        1
mt        1
fy        1
Name: count, Length: 101, dtype: int64

In [13]:
df = df.drop(['budget','adult','imdb_id', 'homepage', 'runtime', 'backdrop_path', 'poster_path', 'original_language', 'original_title', 'popularity', 'production_companies', 'production_countries','release_date','revenue','spoken_languages','status', 'tagline', 'vote_average', 'vote_count'], axis=1)

In [14]:
df

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","[{'cast_id': 9, 'character': 'Joseph Cooper', ...","[{'credit_id': '54cba75b925141678e014d1a', 'de..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de..."
...,...,...,...,...,...,...,...
45011,358980,The Dam on the Yellow River,"Anti-Communist propaganda film, in which the v...",Drama,cold war propaganda,"[{'cast_id': 3, 'character': 'Dorothy Simmons'...","[{'credit_id': '55f004559251413e4501d2ae', 'de..."
45012,359010,Ambush Trail,One of four western films made for PRC by bant...,"Action, Western","sheriff, ranch, jail","[{'cast_id': 2, 'character': 'Curley Thompson'...","[{'credit_id': '55f0540f925141409e0001b0', 'de..."
45013,362463,The Cantor's Son,This musical drama marks the screen debut of M...,NaN,NaN,"[{'cast_id': 2, 'character': ""Saul 'Shloimele'...","[{'credit_id': '5610deab925141478d008164', 'de..."
45014,360808,Doctor's Orders,Leslie Fuller stars as a quack whose son quali...,Comedy,NaN,"[{'cast_id': 1, 'character': 'Bill Blake', 'cr...","[{'credit_id': '5600090e9251412aad00246b', 'de..."
45015,361664,Giano,A family’s old film found in a drawer. A big c...,Documentary,NaN,[],"[{'credit_id': '569e37b9c3a36858e5006b51', 'de..."

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45016 entries, 0 to 45015
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        45016 non-null  int64
 1   title     45016 non-null  object
 2   overview  44751 non-null  object
 3   genres    44520 non-null  object
 4   keywords  34968 non-null  object
 5   cast      45016 non-null  object
 6   crew      45016 non-null  object
dtypes: int64(1), object(6)
memory usage: 2.4+ MB

In [16]:
df.isnull().sum()

id              0
title           0
overview      265
genres        496
keywords    10048
cast            0
crew            0
dtype: int64

In [17]:
df.dropna(inplace=True)
df

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","[{'cast_id': 9, 'character': 'Joseph Cooper', ...","[{'credit_id': '54cba75b925141678e014d1a', 'de..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de..."
...,...,...,...,...,...,...,...
45006,367006,Seasick,Eco-terrorists attack a ship carrying toxic wa...,"Drama, Thriller","sea, ship, toxic, eco terrorism","[{'cast_id': 2, 'character': 'Elena Polakov', ...","[{'credit_id': '563d591cc3a36862da001bb3', 'de..."
45009,366005,Lullaby,A young girl struggles to survive the apocalyp...,"Music, Horror","sibling relationship, musical, zombie","[{'cast_id': 0, 'character': 'Sara', 'credit_i...","[{'credit_id': '5633c83192514129fe0081cb', 'de..."
45010,359195,13 Fighting Men,A group of Union Army soldiers is charged with...,"War, Western",gold,"[{'cast_id': 1, 'character': 'Capt. John Forre...","[{'credit_id': '55f1bf62c3a3683bec0024ad', 'de..."
45011,358980,The Dam on the Yellow River,"Anti-Communist propaganda film, in which the v...",Drama,cold war propaganda,"[{'cast_id': 3, 'character': 'Dorothy Simmons'...","[{'credit_id': '55f004559251413e4501d2ae', 'de..."
45012,359010,Ambush Trail,One of four western films made for PRC by bant...,"Action, Western","sheriff, ranch, jail","[{'cast_id': 2, 'character': 'Curley Thompson'...","[{'credit_id': '55f0540f925141409e0001b0', 'de..."

In [18]:
df.duplicated().sum()

np.int64(23)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...","[{'cast_id': 9, 'character': 'Joseph Cooper', ...","[{'credit_id': '54cba75b925141678e014d1a', 'de..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de..."
...,...,...,...,...,...,...,...
45006,367006,Seasick,Eco-terrorists attack a ship carrying toxic wa...,"Drama, Thriller","sea, ship, toxic, eco terrorism","[{'cast_id': 2, 'character': 'Elena Polakov', ...","[{'credit_id': '563d591cc3a36862da001bb3', 'de..."
45009,366005,Lullaby,A young girl struggles to survive the apocalyp...,"Music, Horror","sibling relationship, musical, zombie","[{'cast_id': 0, 'character': 'Sara', 'credit_i...","[{'credit_id': '5633c83192514129fe0081cb', 'de..."
45010,359195,13 Fighting Men,A group of Union Army soldiers is charged with...,"War, Western",gold,"[{'cast_id': 1, 'character': 'Capt. John Forre...","[{'credit_id': '55f1bf62c3a3683bec0024ad', 'de..."
45011,358980,The Dam on the Yellow River,"Anti-Communist propaganda film, in which the v...",Drama,cold war propaganda,"[{'cast_id': 3, 'character': 'Dorothy Simmons'...","[{'credit_id': '55f004559251413e4501d2ae', 'de..."
45012,359010,Ambush Trail,One of four western films made for PRC by bant...,"Action, Western","sheriff, ranch, jail","[{'cast_id': 2, 'character': 'Curley Thompson'...","[{'credit_id': '55f0540f925141409e0001b0', 'de..."

In [21]:
import ast
df['genres'] = df['genres'].apply(lambda g: [genre.strip() for genre in g.split(',')])
df['keywords'] = df['keywords'].apply(lambda k: [keyword.strip() for keyword in k.split(',')])

In [22]:
df

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","[Action, Science Fiction, Adventure]","[rescue, mission, dream, airplane, paris, fran...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,157336,Interstellar,The adventures of a group of explorers who mak...,"[Adventure, Drama, Science Fiction]","[rescue, future, spacecraft, race against time...","[{'cast_id': 9, 'character': 'Joseph Cooper', ...","[{'credit_id': '54cba75b925141678e014d1a', 'de..."
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secret identity, crime ...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de..."
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[future, society, culture clash, space travel,...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"[Science Fiction, Action, Adventure]","[new york city, superhero, shield, based on co...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de..."
...,...,...,...,...,...,...,...
45006,367006,Seasick,Eco-terrorists attack a ship carrying toxic wa...,"[Drama, Thriller]","[sea, ship, toxic, eco terrorism]","[{'cast_id': 2, 'character': 'Elena Polakov', ...","[{'credit_id': '563d591cc3a36862da001bb3', 'de..."
45009,366005,Lullaby,A young girl struggles to survive the apocalyp...,"[Music, Horror]","[sibling relationship, musical, zombie]","[{'cast_id': 0, 'character': 'Sara', 'credit_i...","[{'credit_id': '5633c83192514129fe0081cb', 'de..."
45010,359195,13 Fighting Men,A group of Union Army soldiers is charged with...,"[War, Western]",[gold],"[{'cast_id': 1, 'character': 'Capt. John Forre...","[{'credit_id': '55f1bf62c3a3683bec0024ad', 'de..."
45011,358980,The Dam on the Yellow River,"Anti-Communist propaganda film, in which the v...",[Drama],[cold war propaganda],"[{'cast_id': 3, 'character': 'Dorothy Simmons'...","[{'credit_id': '55f004559251413e4501d2ae', 'de..."
45012,359010,Ambush Trail,One of four western films made for PRC by bant...,"[Action, Western]","[sheriff, ranch, jail]","[{'cast_id': 2, 'character': 'Curley Thompson'...","[{'credit_id': '55f0540f925141409e0001b0', 'de..."

In [23]:
df['cast'][0]

'[{\'cast_id\': 1, \'character\': \'Dom Cobb\', \'credit_id\': \'52fe4534c3a368484e04de03\', \'gender\': 2, \'id\': 6193, \'name\': \'Leonardo DiCaprio\', \'order\': 0, \'profile_path\': \'/jToSMocaCaS5YnuOJVqQ7S7pr4Q.jpg\'}, {\'cast_id\': 3, \'character\': \'Arthur\', \'credit_id\': \'52fe4534c3a368484e04de0b\', \'gender\': 2, \'id\': 24045, \'name\': \'Joseph Gordon-Levitt\', \'order\': 1, \'profile_path\': \'/zSuXCR6xCKIgo0gWLdp8moMlH3I.jpg\'}, {\'cast_id\': 5, \'character\': \'Ariadne\', \'credit_id\': \'52fe4534c3a368484e04de13\', \'gender\': 1, \'id\': 27578, \'name\': \'Ellen Page\', \'order\': 2, \'profile_path\': \'/paexwBfmlVyzva7q4XgcBdqowmL.jpg\'}, {\'cast_id\': 7, \'character\': \'Eames\', \'credit_id\': \'52fe4534c3a368484e04de1b\', \'gender\': 2, \'id\': 2524, \'name\': \'Tom Hardy\', \'order\': 3, \'profile_path\': \'/4CR1D9VLWZcmGgh4b6kKuY2NOel.jpg\'}, {\'cast_id\': 2, \'character\': \'Saito\', \'credit_id\': \'52fe4534c3a368484e04de07\', \'gender\': 2, \'id\': 3899, \'name\': \'Ken Watanabe\', \'order\': 4, \'profile_path\': \'/v8WQ5wCIZsnqVZn7jQveaDqurox.jpg\'}, {\'cast_id\': 8, \'character\': \'Robert Fischer\', \'credit_id\': \'52fe4534c3a368484e04de1f\', \'gender\': 2, \'id\': 2037, \'name\': \'Cillian Murphy\', \'order\': 5, \'profile_path\': \'/gybXt7gjFCeV67l3jgJtp6Pxm77.jpg\'}, {\'cast_id\': 4, \'character\': \'Mal\', \'credit_id\': \'52fe4534c3a368484e04de0f\', \'gender\': 1, \'id\': 8293, \'name\': \'Marion Cotillard\', \'order\': 6, \'profile_path\': \'/wuEWDK1D2v26KRDIY7DTHBaSdwA.jpg\'}, {\'cast_id\': 6, \'character\': \'Miles\', \'credit_id\': \'52fe4534c3a368484e04de17\', \'gender\': 2, \'id\': 3895, \'name\': \'Michael Caine\', \'order\': 7, \'profile_path\': \'/vvj0JMSFpOajXCE46Hy4dyqSP2U.jpg\'}, {\'cast_id\': 19, \'character\': \'Yusuf\', \'credit_id\': \'52fe4534c3a368484e04de4f\', \'gender\': 2, \'id\': 95697, \'name\': \'Dileep Rao\', \'order\': 8, \'profile_path\': \'/lsnmeKueImKeToe4oNo4YWie4aM.jpg\'}, {\'cast_id\': 9, \'character\': \'Browning\', \'credit_id\': \'52fe4534c3a368484e04de23\', \'gender\': 2, \'id\': 13022, \'name\': \'Tom Berenger\', \'order\': 9, \'profile_path\': \'/gueEBgqv1sWFemMXyI4TJ2peuMA.jpg\'}, {\'cast_id\': 22, \'character\': \'Maurice Fischer\', \'credit_id\': \'52fe4534c3a368484e04de59\', \'gender\': 2, \'id\': 4935, \'name\': \'Pete Postlethwaite\', \'order\': 10, \'profile_path\': \'/5nbSzrwyDcLhC15buncGdrQqJ8e.jpg\'}, {\'cast_id\': 10, \'character\': \'Nash\', \'credit_id\': \'52fe4534c3a368484e04de27\', \'gender\': 2, \'id\': 526, \'name\': \'Lukas Haas\', \'order\': 11, \'profile_path\': \'/1n1CTF6fi52BF407iQU6aMMKWFU.jpg\'}, {\'cast_id\': 89, \'character\': \'Blonde\', \'credit_id\': \'52fe4534c3a368484e04de99\', \'gender\': 1, \'id\': 66441, \'name\': \'Talulah Riley\', \'order\': 12, \'profile_path\': \'/cmA8krd4hpPC9kWSF9wpSx6ffMt.jpg\'}, {\'cast_id\': 92, \'character\': \'Japanese Security Guard\', \'credit_id\': \'57d488dec3a3685568007ba1\', \'gender\': 0, \'id\': 173212, \'name\': \'Tohoru Masamune\', \'order\': 13, \'profile_path\': \'/hCevJsAh0RByhKzRZwrGXlW64Oo.jpg\'}, {\'cast_id\': 93, \'character\': \'Phillipa (5 years)\', \'credit_id\': \'57d488f8c3a368154b0011a1\', \'gender\': 1, \'id\': 967376, \'name\': \'Taylor Geare\', \'order\': 14, \'profile_path\': \'/2ITSJXHWdkAFWu1hqIfr53zib8J.jpg\'}, {\'cast_id\': 94, \'character\': \'Phillipa (3 years)\', \'credit_id\': \'57d48919925141382f0011ca\', \'gender\': 1, \'id\': 973135, \'name\': \'Claire Geare\', \'order\': 15, \'profile_path\': \'/gLU4bc2Cr7GgLeIaZJwihmDcJ64.jpg\'}, {\'cast_id\': 95, \'character\': \'James (3 years)\', \'credit_id\': \'57d48aca925141369d00113d\', \'gender\': 2, \'id\': 1677266, \'name\': \'Johnathan Geare\', \'order\': 16, \'profile_path\': \'/zorFsXj371juf6S9RuX2OxOWfaP.jpg\'}, {\'cast_id\': 96, \'character\': "Saito\'s Attendant", \'credit_id\': \'57d48b45c3a3680b9f00179e\', \'gender\': 2, \'id\': 56120, \'name\': \'Yuji Okumoto\', \'order\': 17, \'profile_path\': \'/eVq0Od53a8JdfYLGHxkBboOtsIe.jpg\'}, {\'cast_id\': 97, \'character\': \'Elderly Bald Man\', \'credit_id\': \'57d48b59c3a3685568007cd7\', \'gender\': 2, \'id\': 2246, \'name\': \'Earl Cameron\', \'order\': 18, \'profile_path\': \'/4bDKeRU96RxpJ2Uv8x2yrjCmGks.jpg\'}, {\'cast_id\': 98, \'character\': \'Lawyer\', \'credit_id\': \'57d48b6dc3a3680ccd001433\', \'gender\': 2, \'id\': 1677267, \'name\': \'Ryan Hayward\', \'order\': 19, \'profile_path\': \'/i43V4v95o2n60HSmcHuiYWbHAVT.jpg\'}, {\'cast_id\': 99, \'character\': \'Flight Attendant\', \'credit_id\': \'57d48b84925141382f0012af\', \'gender\': 1, \'id\': 1334309, \'name\': \'Miranda Nolan\', \'order\': 20, \'profile_path\': \'/lwIOE3hSz4M3l3dab0UrhoK2Xt6.jpg\'}, {\'cast_id\': 100, \'character\': \'Cab Driver\', \'credit_id\': \'57d53da09251415c1e000263\', \'gender\': 2, \'id\': 535, \'name\': \'Russ Fega\', \'order\': 21, \'profile_path\': \'/7JFQueMbXqGIz16wKBlok7WfNNz.jpg\'}, {\'cast_id\': 101, \'character\': \'Thin Man\', \'credit_id\': \'57d53db4c3a368556800ce41\', \'gender\': 2, \'id\': 72864, \'name\': \'Tim Kelleher\', \'order\': 22, \'profile_path\': \'/y1sYHWkXNeW09Iy2BUed4SveKl7.jpg\'}, {\'cast_id\': 102, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53e46c3a36812b2000308\', \'gender\': 1, \'id\': 1677498, \'name\': \'Coralie Dedykere\', \'order\': 23, \'profile_path\': \'/kv7RsuDTCYpPpIkadtx9sXkEENw.jpg\'}, {\'cast_id\': 103, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53ee6c3a3686e3c000cd9\', \'gender\': 0, \'id\': 13695, \'name\': \'Silvie Laguna\', \'order\': 24, \'profile_path\': \'/rbigEHdNk1DBAgj9ge7Q1CqhdFD.jpg\'}, {\'cast_id\': 104, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53efcc3a36813230002f5\', \'gender\': 2, \'id\': 133257, \'name\': \'Virgile Bramly\', \'order\': 25, \'profile_path\': \'/bHtRBA6UNeePq9LXk6vwzNNbIYs.jpg\'}, {\'cast_id\': 105, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d53fde9251415c1e000324\', \'gender\': 2, \'id\': 1677507, \'name\': \'Nicolas Clerc\', \'order\': 26, \'profile_path\': \'/aYchs3lYO9RvhmClO1xLkocTFZq.jpg\'}, {\'cast_id\': 106, \'character\': \'Bridge Sub Con\', \'credit_id\': \'57d5405f9251415bb300037f\', \'gender\': 2, \'id\': 1536351, \'name\': \'Jean-Michel Dagory\', \'order\': 27, \'profile_path\': \'/wU0a4eyOlIinZVGnbIs98KRFo9D.jpg\'}, {\'cast_id\': 107, \'character\': \'Lobby Sub Con\', \'credit_id\': \'57d540c7c3a36813230003bc\', \'gender\': 2, \'id\': 203087, \'name\': \'Marc Raducci\', \'order\': 28, \'profile_path\': \'/amulXn9DCowb8OGZJMrcw34qSYZ.jpg\'}]'

In [ ]:
#taking out top 3 cast members
def cast(obj):
    l = []
    counter = 0
    for i in ast.literal_eval(obj) if isinstance(obj, str) else []:
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [25]:
df['cast'] = df['cast'].apply(cast)

In [26]:
df['cast']

0        [Leonardo DiCaprio, Joseph Gordon-Levitt, Elle...
1        [Matthew McConaughey, Jessica Chastain, Anne H...
2            [Christian Bale, Michael Caine, Heath Ledger]
3         [Sam Worthington, Zoe Saldana, Sigourney Weaver]
4           [Robert Downey Jr., Chris Evans, Mark Ruffalo]
                               ...
45006            [Katrin Cartlidge, John Castle, Bob Peck]
45009                 [Mary Kate Wiles, Monica Joy Sherer]
45010        [Grant Williams, Brad Dexter, Carole Mathews]
45011      [Anita Ekberg, Georges Marchal, Franca Bettoia]
45012         [Bob Steele, Syd Saylor, I. Stanford Jolley]
Name: cast, Length: 34763, dtype: object

In [27]:
df['crew'][0]

"[{'credit_id': '56e8462cc3a368408400354c', 'department': 'Sound', 'gender': 2, 'id': 947, 'job': 'Original Music Composer', 'name': 'Hans Zimmer', 'profile_path': '/7IjJpvGtCfY0DsritmfCh2iX9I4.jpg'}, {'credit_id': '52fe4534c3a368484e04de55', 'department': 'Writing', 'gender': 2, 'id': 525, 'job': 'Screenplay', 'name': 'Christopher Nolan', 'profile_path': '/7OGmfDF4VHLLgbjxuEwTj3ga0uQ.jpg'}, {'credit_id': '52fe4534c3a368484e04de4b', 'department': 'Directing', 'gender': 2, 'id': 525, 'job': 'Director', 'name': 'Christopher Nolan', 'profile_path': '/7OGmfDF4VHLLgbjxuEwTj3ga0uQ.jpg'}, {'credit_id': '52fe4534c3a368484e04de2d', 'department': 'Production', 'gender': 2, 'id': 525, 'job': 'Producer', 'name': 'Christopher Nolan', 'profile_path': '/7OGmfDF4VHLLgbjxuEwTj3ga0uQ.jpg'}, {'credit_id': '52fe4534c3a368484e04de33', 'department': 'Production', 'gender': 1, 'id': 556, 'job': 'Producer', 'name': 'Emma Thomas', 'profile_path': '/f12TsNlAEomPdwxueS7ImMoJtsP.jpg'}, {'credit_id': '52fe4534c3a368484e04de3f', 'department': 'Camera', 'gender': 2, 'id': 559, 'job': 'Director of Photography', 'name': 'Wally Pfister', 'profile_path': '/tyYtVatXW16EM7NYJZkxI3K2NQi.jpg'}, {'credit_id': '52fe4534c3a368484e04de6b', 'department': 'Production', 'gender': 0, 'id': 561, 'job': 'Casting', 'name': 'John Papsidera', 'profile_path': '/quM89TMS6BncoIh4NdlWugXVhuF.jpg'}, {'credit_id': '52fe4534c3a368484e04de45', 'department': 'Editing', 'gender': 0, 'id': 3904, 'job': 'Editor', 'name': 'Lee Smith', 'profile_path': '/5XNVKGYwQraa4LYk0pjRhvdC3c1.jpg'}, {'credit_id': '52fe4534c3a368484e04de8f', 'department': 'Art', 'gender': 0, 'id': 10958, 'job': 'Set Decoration', 'name': 'Douglas A. Mowat', 'profile_path': None}, {'credit_id': '52fe4534c3a368484e04de7d', 'department': 'Art', 'gender': 2, 'id': 8705, 'job': 'Art Direction', 'name': 'Brad Ricker', 'profile_path': None}, {'credit_id': '52fe4534c3a368484e04de89', 'department': 'Art', 'gender': 2, 'id': 21984, 'job': 'Set Decoration', 'name': 'Larry Dias', 'profile_path': None}, {'credit_id': '52fe4534c3a368484e04de5f', 'department': 'Production', 'gender': 0, 'id': 41018, 'job': 'Executive Producer', 'name': 'Chris Brigham', 'profile_path': '/lbWFcY3aVB8vG7tWwBXILJM8jyH.jpg'}, {'credit_id': '52fe4534c3a368484e04de65', 'department': 'Production', 'gender': 0, 'id': 54211, 'job': 'Executive Producer', 'name': 'Thomas Tull', 'profile_path': '/5UG4FK7rsmhzJDYxpU28acqfxtu.jpg'}, {'credit_id': '579d07fe9251411b36008736', 'department': 'Sound', 'gender': 0, 'id': 68016, 'job': 'Orchestrator', 'name': 'Kevin Kaska', 'profile_path': '/azlSu8Sz9QGeK3xgQS9p3ZvR9q9.jpg'}, {'credit_id': '52fe4534c3a368484e04de77', 'department': 'Art', 'gender': 0, 'id': 76054, 'job': 'Art Direction', 'name': 'Luke Freeborn', 'profile_path': None}, {'credit_id': '52fe4534c3a368484e04de83', 'department': 'Art', 'gender': 2, 'id': 969743, 'job': 'Art Direction', 'name': 'Dean Wolcott', 'profile_path': None}, {'credit_id': '52fe4534c3a368484e04de71', 'department': 'Art', 'gender': 0, 'id': 1271644, 'job': 'Production Design', 'name': 'Guy Hendrix Dyas', 'profile_path': None}, {'credit_id': '52fe4534c3a368484e04de95', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1271645, 'job': 'Costume Design', 'name': 'Jerry Kurland', 'profile_path': None}]"

In [ ]:
#taking out only director as crew member
def director(obj):
    l = []
    for i in ast.literal_eval(obj) if isinstance(obj, str) else []:
        if i['job'] == 'Director':
            l.append(i['name'])
            break
    return l

In [29]:
df['crew'] = df['crew'].apply(director)

In [30]:
df.head(2)

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","[Action, Science Fiction, Adventure]","[rescue, mission, dream, airplane, paris, fran...","[Leonardo DiCaprio, Joseph Gordon-Levitt, Elle...",[Christopher Nolan]
1,157336,Interstellar,The adventures of a group of explorers who mak...,"[Adventure, Drama, Science Fiction]","[rescue, future, spacecraft, race against time...","[Matthew McConaughey, Jessica Chastain, Anne H...",[Christopher Nolan]

In [31]:
df['overview'] = df['overview'].apply(lambda x: x.split())

In [32]:
df.head()

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"[Cobb,, a, skilled, thief, who, commits, corpo...","[Action, Science Fiction, Adventure]","[rescue, mission, dream, airplane, paris, fran...","[Leonardo DiCaprio, Joseph Gordon-Levitt, Elle...",[Christopher Nolan]
1,157336,Interstellar,"[The, adventures, of, a, group, of, explorers,...","[Adventure, Drama, Science Fiction]","[rescue, future, spacecraft, race against time...","[Matthew McConaughey, Jessica Chastain, Anne H...",[Christopher Nolan]
2,155,The Dark Knight,"[Batman, raises, the, stakes, in, his, war, on...","[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secret identity, crime ...","[Christian Bale, Michael Caine, Heath Ledger]",[Christopher Nolan]
3,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[future, society, culture clash, space travel,...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
4,24428,The Avengers,"[When, an, unexpected, enemy, emerges, and, th...","[Science Fiction, Action, Adventure]","[new york city, superhero, shield, based on co...","[Robert Downey Jr., Chris Evans, Mark Ruffalo]",[Joss Whedon]

In [33]:
#concatinatin all lists fot new tags columns 
# fist remove white spaces from all the elements in the list to avoid duplicacy

df['genres'] = df['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
df['keywords'] = df['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
df['cast'] = df['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
df['crew'] = df['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [34]:
df.head()

,id,title,overview,genres,keywords,cast,crew
0,27205,Inception,"[Cobb,, a, skilled, thief, who, commits, corpo...","[Action, ScienceFiction, Adventure]","[rescue, mission, dream, airplane, paris, fran...","[LeonardoDiCaprio, JosephGordon-Levitt, EllenP...",[ChristopherNolan]
1,157336,Interstellar,"[The, adventures, of, a, group, of, explorers,...","[Adventure, Drama, ScienceFiction]","[rescue, future, spacecraft, raceagainsttime, ...","[MatthewMcConaughey, JessicaChastain, AnneHath...",[ChristopherNolan]
2,155,The Dark Knight,"[Batman, raises, the, stakes, in, his, war, on...","[Drama, Action, Crime, Thriller]","[joker, sadism, chaos, secretidentity, crimefi...","[ChristianBale, MichaelCaine, HeathLedger]",[ChristopherNolan]
3,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[future, society, cultureclash, spacetravel, s...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
4,24428,The Avengers,"[When, an, unexpected, enemy, emerges, and, th...","[ScienceFiction, Action, Adventure]","[newyorkcity, superhero, shield, basedoncomic,...","[RobertDowneyJr., ChrisEvans, MarkRuffalo]",[JossWhedon]

In [35]:
# creating tags column
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [36]:
df.sample()

,id,title,overview,genres,keywords,cast,crew,tags
22040,53953,The Tooth Fairy,"[A, woman, and, her, daughter, (Nicole, Muñoz)...",[Horror],"[gore, slasher, singlemother, toothfairy, wood...","[LochlynMunro, ChandraWest, SteveBacic]",[ChuckBowman],"[A, woman, and, her, daughter, (Nicole, Muñoz)..."

In [37]:
df[df['id'] == 651]

,id,title,overview,genres,keywords,cast,crew,tags
3369,651,M*A*S*H,"[The, staff, of, a, Korean, War, field, hospit...","[Comedy, Drama, War]","[americanfootball, darkcomedy, surgeon, americ...","[DonaldSutherland, ElliottGould, TomSkerritt]",[RobertAltman],"[The, staff, of, a, Korean, War, field, hospit..."

In [38]:
new_df = df[['id', 'title', 'tags']]
new_df

,id,title,tags
0,27205,Inception,"[Cobb,, a, skilled, thief, who, commits, corpo..."
1,157336,Interstellar,"[The, adventures, of, a, group, of, explorers,..."
2,155,The Dark Knight,"[Batman, raises, the, stakes, in, his, war, on..."
3,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
4,24428,The Avengers,"[When, an, unexpected, enemy, emerges, and, th..."
...,...,...,...
45006,367006,Seasick,"[Eco-terrorists, attack, a, ship, carrying, to..."
45009,366005,Lullaby,"[A, young, girl, struggles, to, survive, the, ..."
45010,359195,13 Fighting Men,"[A, group, of, Union, Army, soldiers, is, char..."
45011,358980,The Dam on the Yellow River,"[Anti-Communist, propaganda, film,, in, which,..."
45012,359010,Ambush Trail,"[One, of, four, western, films, made, for, PRC..."

In [39]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))
new_df

C:\Users\infor\AppData\Local\Temp\ipykernel_8028\2970228488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

,id,title,tags
0,27205,Inception,"Cobb, a skilled thief who commits corporate es..."
1,157336,Interstellar,The adventures of a group of explorers who mak...
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
4,24428,The Avengers,When an unexpected enemy emerges and threatens...
...,...,...,...
45006,367006,Seasick,Eco-terrorists attack a ship carrying toxic wa...
45009,366005,Lullaby,A young girl struggles to survive the apocalyp...
45010,359195,13 Fighting Men,A group of Union Army soldiers is charged with...
45011,358980,The Dam on the Yellow River,"Anti-Communist propaganda film, in which the v..."
45012,359010,Ambush Trail,One of four western films made for PRC by bant...

In [40]:
new_df['tags'][0]

'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious. Action ScienceFiction Adventure rescue mission dream airplane paris france virtualreality kidnapping philosophy spy allegory manipulation carcrash heist memory architecture losangeles california dreamworld subconscious LeonardoDiCaprio JosephGordon-Levitt EllenPage ChristopherNolan'

In [41]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())
new_df.head()

C:\Users\infor\AppData\Local\Temp\ipykernel_8028\883946691.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

       id            title                                               tags
0   27205        Inception  cobb, a skilled thief who commits corporate es...
1  157336     Interstellar  the adventures of a group of explorers who mak...
2     155  The Dark Knight  batman raises the stakes in his war on crime. ...
3   19995           Avatar  in the 22nd century, a paraplegic marine is di...
4   24428     The Avengers  when an unexpected enemy emerges and threatens...

-------------------------------------------------------------------------------------------------------------------------------------------------

Text Vectoization using Bag of Words Technique

In [42]:
# !pip install scikit-learn

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english') # remove english words like is, am, are, the, etc

In [44]:
vectors = cv.fit_transform(new_df['tags']).toarray() #converting sparse matrix into numpy array
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [45]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [47]:
# applying stemming ------------------------------ i.e removing same kind of words like play, playing, played, plays, etc to same work play

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [48]:
# !pip install nltk

In [49]:
def stem(txt):
    y = []

    for i in txt.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [50]:
ps.stem('loving')

'love'

In [51]:
new_df['tags'][0]

'cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious. action sciencefiction adventure rescue mission dream airplane paris france virtualreality kidnapping philosophy spy allegory manipulation carcrash heist memory architecture losangeles california dreamworld subconscious leonardodicaprio josephgordon-levitt ellenpage christophernolan'

In [52]:
stem('cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious. action sciencefiction adventure rescue mission dream airplane paris france virtualreality kidnapping philosophy spy allegory manipulation carcrash heist memory architecture losangeles california dreamworld subconscious leonardodicaprio josephgordon-levitt ellenpage christophernolan')

'cobb, a skill thief who commit corpor espionag by infiltr the subconsci of hi target is offer a chanc to regain hi old life as payment for a task consid to be impossible: "inception", the implant of anoth person\' idea into a target\' subconscious. action sciencefict adventur rescu mission dream airplan pari franc virtualr kidnap philosophi spi allegori manipul carcrash heist memori architectur losangel california dreamworld subconsci leonardodicaprio josephgordon-levitt ellenpag christophernolan'

In [53]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\infor\AppData\Local\Temp\ipykernel_8028\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [54]:
# now again vectorising it 

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english') # remove english words like is, am, are, the, etc

In [55]:
vectors = cv.fit_transform(new_df['tags']).toarray() #converting sparse matrix into numpy array
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [56]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [57]:
# Now Calculating distance among each movie in a 34k vector space, we will calcualte cosine distance i.e angle b/w each vectors, not euclidean distance
# euclidian distance is not a good measure for higher dimensional data, " curse of Dimensionality "

# DISTANCE AND SIMILARITY IS INVERSELY PROPORTIONAL, i.e IF THE DISTANCE B/W TWO VECTORS IS MORE THEN THE SIMILARITY IS LESS

In [ ]:
# cosine similarity

from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix

# Convert to sparse matrix
sparse_vectors = csr_matrix(vectors)

# Function to compute sparse similarity
def compute_sparse_similarity(sparse_matrix, top_k=500):
    num_rows = sparse_matrix.shape[0]
    similarity_sparse = {}

    for i in range(num_rows):
        row_sim = cosine_similarity(sparse_matrix[i], sparse_matrix).flatten()
        top_indices = row_sim.argsort()[-top_k-1:-1]  # Get top k similar items
        similarity_sparse[i] = {idx: row_sim[idx] for idx in top_indices}

    return similarity_sparse

# Compute sparse similarity
similarity_sparse = compute_sparse_similarity(sparse_vectors, top_k=500)

print("Computed sparse cosine similarity successfully!")

In [ ]:
def similarity_dict_to_matrix(similarity_dict, num_movies, top_k=500):
    
    similarity_matrix = np.zeros((num_movies, top_k))  # Initialize empty matrix
    
    for i in range(num_movies):
        if i in similarity_dict:
            # Get top-K similar movies and their scores
            sorted_similarities = sorted(similarity_dict[i].items(), key=lambda x: x[1], reverse=True)[:top_k]
            
            # Extract only similarity scores (ignoring movie indices)
            similarity_matrix[i, :len(sorted_similarities)] = [score for _, score in sorted_similarities]
    
    return similarity_matrix

# Convert dictionary to similarity matrix (keeping top-20 closest movies)
num_movies = sparse_vectors.shape[0]  
similarity_matrix = similarity_dict_to_matrix(similarity_sparse, num_movies, top_k=500)

# Print matrix shape and sample row
print("Similarity Matrix Shape:", similarity_matrix.shape)
print("Example row (similarity scores of 50 closest movies):\n", similarity_matrix)

In [ ]:
similarity_matrix.shape

In [ ]:
similarity_matrix[0]

In [ ]:
import random

def recommend(movie, n=20):
    try:
        # Get movie index
        movie_index = new_df[new_df['title'] == movie].index[0]
            
        # Get similarity scores of the movie (list of tuples with index and score)
        similarity_scores = list(enumerate(similarity_matrix[movie_index])) 
        
        # Sort movies based on similarity scores
        sorted_similarities = sorted(similarity_scores, key=lambda x: x[1], reverse=True)[1:251]
        
        # Get the indices of the top 250 similar movies (excluding itself)
        random.shuffle(sorted_similarities)  # Shuffle the top 250 movies

        # Select 'n' random movies from the top 250 similar movies
        selected_titles = [new_df['title'].iloc[i] for i, _ in sorted_similarities[:n]]
        
    except IndexError:
        print(f"❌ '{movie}' not found! Suggesting 20 random movies instead.")
        selected_titles = new_df['title'].sample(n).tolist()

    print("\n".join(selected_titles))

In [ ]:
recommend('Get Out')

In [ ]:
df[df['title'] == "Suicide Squad"]['genres']

In [ ]:
df[df['title'] == "M*A*S*H"]['genres']

In [ ]:
new_df.sample(5)

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
pickle.dump(similarity_matrix,open('similarity.pkl','wb'))